### ISSUE TITLE
Target entities without components

### ISSUE THREAD

**Issue by isovector** [jonascarpay/apecs#10]
It'd be nice to be able to target entities that don't have a particular component.

For example, I'd like to be able to rmap both of the following functions simultaneously, and get the correct behavior:

```haskell
defaultUpdatePos :: (Position, Velocity) -> Position
updatePosButHitWalls :: (Position, Velocity, Collision) -> (Position, Velocity)
```

proposed syntax for this might be something like:

```haskell
defaultUpdatePos :: (Position, Velocity, Without Collision) -> Position
defaultUpdatePos (Position p, Velocity v, Without) = ...
```

**Comment by isovector** [comment]
Alternatively, could provide some sort of `System`-aware mapping, and provide an `MonadZero` instance for `System` which would allow `guard`ing on a failed `exists` check.

**Comment by isovector** [comment]
I got something like this working; it's not pretty, but it works:

```haskell
anyone :: Applicative m => m Bool
anyone = const $ pure True

without
    :: forall c e world
     . Has world c
    => Entity e
    -> System world Bool
without e = fmap not . exists $ cast e @c

mmap
    :: forall world r w r' w'
     . ( Has world r'
       )
    => (Entity r' -> System world r)
    -> (Entity w' -> w -> System world ())
    -> (Entity r' -> System world Bool)
    -> (r -> System world w)
    -> System world ()
mmap mget mset p f = do
  them <- owners @_ @r'
  S.forM_ them $ \who -> do
    pwho <- p who
    when pwho $ do
      dat <- mget who
      x <- f dat
      mset (cast who :: Entity w') x
```

```haskell
defaultUpdatePos = mmap getUnsafe set (without @Collision) $ ...
updatePosButHitWalls = mmap getUnsafe set anyone $ ...
```

**Comment by jonascarpay** [comment]
If I understand correctly, you want different behaviour depending on whether or not an entity has some component. Would `wmap` work in your case?
```haskell
updatePos :: Safe (Position, Velocity, Collision) -> (Position, Velocity)
updatePos (Safe (Just p, Just v, Nothing)) -> (p+v, v)
updatePos (Safe (Just p, Just v, Just c)) -> (p,0)
updatePos (Safe _) -> error "impossible"

system = wmap updatePos
```

**Comment by isovector** [comment]
`wmap` doesn't seem to find any entities with `Just, Just, Nothing` when I tried it. I can't think of how it possibly could and never trigger the `impossible` branch here.

Even if it did, however, it's a pretty heavy interface for a pattern I'm finding pretty common.

**Comment by jonascarpay** [comment]
That's odd, [this](http://lpaste.net/5997871775315132416) works fine on my end.
Anyway, I see your point, it's definitely verbose and I've run into this pattern before. Essentially, you'd want some sort of hybrid between `rmap` and `wmap`, but I'm not sure what the best type signature would be for `mmap`. There's also a bunch of potential implementations, like making a slice and mapping over it, or using `cimapM_` and getting/setting the extra component(s) manually.

**Comment by jonascarpay** [comment]
I think I've found a solution. Considering the fact that (,) represents a conjunction, turns out you can just define a constructor for inversion, `Not a = Not`, `Maybe` that belongs to every entity, or possibly even Either for disjunction. A happy second result is that, by also making an Entity a component, this solved the problem of 8 different mapping functions, you should only ever need cmap(M_) now. This code is live on the dev branch, I'll merge it once I'm sure this is a good idea.

```haskell
-- Apply gravity to non-flying enemies
cmap $ \(Velocity v, Not :: Not Flying) -> Velocity (v - V2 0 1)
-- Step positions
cmap $ \(Position p, Velocity v) -> Position (v+p)
-- For all entities with a position, print their entity number and whether they are the player.
cmapM_ $ \(Position _, Entity e, p :: Maybe Player) -> liftIO . print $ (e, p)
```

**Comment by isovector** [comment]
Is it possible to encode the invariant that no component can have eg `Flying` and `Not Flying` simultaneously?

**Comment by jonascarpay** [comment]
What do you mean by encoding? `Not a` can be used with any component `a` and always has the same behaviour, it inverts `explExists` of `a`'s underlying store, so a membership check on a `(a, Not a)` always fails.
