### ISSUE TITLE
Template Haskell function requires me to import some symbols unqualified

### ISSUE THREAD

**Issue by glocq** [jonascarpay/apecs#116]
(More detail available [here](https://discourse.haskell.org/t/how-does-template-haskell-play-with-qualified-names/7837))
(My specific issue is with `apecs-stm`, but I am fairly certain the issue is also present in `apecs`)

The `mkWorld` function features (among others) `mkName "Has"`, which generates the type constructor `Has`. This requires me to import `Has` unqualified. Forcing this decision (whether and how to import certain symbols) on the user seems problematic.

_Possible fix:_ It was suggested (see link above) that expressions like `mkName "Has"` be replaced with `''Has`, which _might_ generate the right symbol automatically. Unfortunately, I cannot guarantee that this would work, since I am not familiar with Template Haskell. I am hoping that someone more experienced can confirm/invalidate this.

**Comment by jonascarpay** [comment]
Thanks for looking into this. Seems like it's worth it to at least open a PR changing to `''Has`, and then seeing if CI complains
