### ISSUE TITLE
`Not` component first when `cmap`ping causes empty action set

### ISSUE THREAD

**Issue by robinp** [jonascarpay/apecs#14]
I have a component `Deleted`, mostly not tagged on any entity. If I `cmap $ \(Not :: Not Deleted, ...) -> ...`, none of the entities get updated, even if `Deleted` is not on any of them.

**Comment by jonascarpay** [comment]
We cannot feasibly iterate over all members that do not have a certain component, as it could potentially include every possible integer.
So, `Not` should never occur in the first argument of ~cmap~, and on the development branch, this is already a type error. On the master branch, it just returns an empty list.
There are two ways to work around this;
1. Ideally, use a component that you can iterate over and have `Not` in the second position, e.g. `(_ :: SomeComponent, _ :: Not Deleted)`
2. If the entities have no other component in common, you can iterate manually with something like:
```haskell
EntityCounter max <- Global
forM_ [0..max] $ \e -> do
  --check whether entity e has Deleted
  --do things
```
