### ISSUE TITLE
Map name conflict

### ISSUE THREAD

**Issue by ghost** [jonascarpay/apecs#15]
`Map` from apecs conflicts with `Map` from `Data.Map` (and anything that exports it)

This is minor, but it would be nice to be able to use apecs and protolude without
any conflicts.

I don't think this necessitates a new release or anything, but it would be nice to have included
whenever version 0.4 comes out

**Comment by cjenn** [comment]
Also, `get` conflicts with [`Control.Monad.State`](https://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-State-Lazy.html), and `getAll` conflicts with [`Data.Monoid`](https://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Monoid.html#t:All)

**Comment by jonascarpay** [comment]
I'm not sure about `get` and `getAll`, but `Map` does need a new name. I also feel something like a `HashMap` would be useful, at which point the normal map can be renamed to something like `ImmutableMap`

**Comment by jonascarpay** [comment]
I've decided that protolude interoperability is not a priority right now. New functions have been introduced with names that deliberately reuse those of similar functions popular libraries, and it has not been a problem for me yet.

If you disagree, feel free to comment/reopen this issue.
