### ISSUE TITLE
Add better error messages for empty systems

### ISSUE THREAD

**Issue by cjenn** [jonascarpay/apecs#16]
Right now, when I try to run a system without adding anything to it, I get:

    Prelude.foldl1: Empty List

This should be replaced with a more helpful message.

**Comment by jonascarpay** [comment]
Sorry for the late response. I can't reproduce this issue, I think it's been fixed with the 0.5 update. I'm closing this issue, feel free to reopen if you can still reproduce the problem on the latest version.
