### ISSUE TITLE
C memory errors in apecs-physics

### ISSUE THREAD

**Issue by jonascarpay** [jonascarpay/apecs#22]
`free(): invalid next size (fast)`
Double free error in the constraints example. I haven't been able to consistently reproduce the issue, but it seems to be related to constraints and have appeared in 0.3.

**Comment by jonascarpay** [comment]
* As far as I can tell, the most reliable way to reproduce is to grab a shape, and move the cursor (offscreen?)
* Only occurs after grabbing (and possibly releasing) a shape.
* Error messages sometimes appear when _closing_ the application
* I added print statements before all `free` calls (see branch), in both apecs-physics and Chipmunk, and none fires before an error message. What free triggers the error?
* Sometimes it's another error message, like
  * `double free or corruption (out)`
  * `free(): invalid size`
  * `munmap_chunk(): invalid pointer`

**Comment by jonascarpay** [comment]
afaict this doesn't occur when running through stack on a mac. if you're reading this, and you're experiencing this issue on some other configuration than nixos + `nix-shell --run constraints`, let me know.

**Comment by fjvallarino** [comment]
@jonascarpay Hi! I can confirm I'm experiencing this issue and I can replicate it. I'm running the `Constraints.hs` example on Manjaro (Arch based), using Stackage LTS 13.13. Not using Nix, just standard Stack on Linux. After dragging one of the objects, I get the same error you mentioned above:

```
apecs-physics: Initializing new Space, Chipmunk v7.0.2 (Debug Enabled)
apecs-physics: Compile with the -frelease (cabal) or --flag apecs-physics:release (stack) to disable debug mode and runtime assertion checks
free(): invalid next size (fast)
[1]    3134 abort (core dumped)  stack run
```

The issue happens consistently and I don't need to drag the cursor outside the container window (the window manager is xmonad).

Let me know if I can provide more information. Thanks!

**Comment by jonascarpay** [comment]
This seems to have been caused by #44.
