### ISSUE TITLE
Are systems just rules?

### ISSUE THREAD

**Issue by JBetz** [jonascarpay/apecs#24]
Do you know what distinguishes entity-component-systems from rule-based systems? I'm curious because I've been trying to layer a rules engine in Haskell ontop of `reflex` that might be better off using something like `apecs`.

My inspiration came from a declarative programming framework called [precept](https://github.com/CoNarrative/precept) that's based on logic-programming and rule-based systems.

In `precept` you have facts and rules, which correspond almost exactly to components and systems. Entities are then just aggregations of facts with the same id. New facts are added by user inputs, and rules are fired if their conditions are met, the consequences of which can be adding or removing facts. The conditions and consequences being the left hand side and right hand side of a lambda passed to `cmap`.

I'm sure there's an important distinction between these frameworks, even if only in perspective, but I haven't spent too much time with either to really say. Abstractly, they both seem to be based on defining application logic in terms of rules, and modeling data as points rather than products.

@alex-dixon might also have some input on this.

**Comment by jonascarpay** [comment]
Let me know if I'm misunderstanding something, I don't know clojure or rule-based systems, but I think there's a big difference in that rules are entirely declarative, whereas systems are imperative. You have to provide the control flow yourself, there is no "when X happens, do Y", there is only "check if X has happened, and if so, do Y".
A simple way to emulate that behavior is by using STM; you run a system continuously on its own thread, and STM will cause it to idle until any of its inputs change.
Another option (that would be really cool) is to implement a Rete network/rule engine on top of apecs, but I don't know the algorithm so I can't comment on how easy that would be.

**Comment by JBetz** [comment]
> Let me know if I'm misunderstanding something, I don't know clojure or rule-based systems, but I think there's a big difference in that rules are entirely declarative, whereas systems are imperative. You have to provide the control flow yourself, there is no "when X happens, do Y", there is only "check if X has happened, and if so, do Y".

I see. And yeah, that clears up the distinction for me. :)

> A simple way to emulate that behavior is by using STM; you run a system continuously on its own thread, and STM will cause it to idle until any of its inputs change.

Neat. I'm guessing that it wouldn't work as well for games when you want to redraw the full canvas at regular intervals, but maybe if you're only doing partial updates? That would make it good enough for the DOM-based UIs, though wiring it into something like `reflex-dom` would be whole other challenge.

> Another option (that would be really cool) is to implement a Rete network/rule engine on top of apecs, but I don't know the algorithm so I can't comment on how easy that would be.

That's what `precept` does, and what I thought I'd need to do, but I'd much rather see how far I can get with the STM approach first.

But yeah, thanks for the feedback. I'm definitely going to explore the possibility of building a rule-based system on top of `apecs`. I like FRP well enough, but I want to go beyond it, and moving towards some sort of declarative ECS seems like a very logical progression.

**Comment by jonascarpay** [comment]
> Neat. I'm guessing that it wouldn't work as well for games when you want to redraw the full canvas at regular intervals, but maybe if you're only doing partial updates?

You don't want to run intensive numerical calculations on STM, but I've been toying with running AI threads on STM, and that works out pretty well.

> I'm definitely going to explore the possibility of building a rule-based system on top of apecs.

Alright, good luck. I'll push `apecs-stm` to hackage tonight. Let me know if you have any questions about the apecs side of things.
