### ISSUE TITLE
Inaccurate version bounds in several `apecs` Hackage releases

### ISSUE THREAD

**Issue by hvr** [jonascarpay/apecs#25]
As can be seen at

https://matrix.hackage.haskell.org/package/apecs@1548960197

every release of `apecs` was affected by having incorrect version bounds.

In my function as a Hackage Trustee I went ahead and tried to reverse engineer some of the omitted bounds and performed respective [Hackage metadata revisions](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md):

 - https://hackage.haskell.org/package/apecs-0.1.0.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.1.1.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.0.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.0.1/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.0.2/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.0.3/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.1.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.1.1/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.2.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.3.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.1/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.2/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.3/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.4/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.5/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.6/revisions/
 - https://hackage.haskell.org/package/apecs-0.2.4.7/revisions/
 - https://hackage.haskell.org/package/apecs-0.3.0.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.3.0.1/revisions/
 - https://hackage.haskell.org/package/apecs-0.3.0.2/revisions/
 - https://hackage.haskell.org/package/apecs-0.4.0.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.4.0.1/revisions/
 - https://hackage.haskell.org/package/apecs-0.4.1.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.4.1.1/revisions/
 - https://hackage.haskell.org/package/apecs-0.5.0.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.5.1.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.5.1.1/revisions/
 - https://hackage.haskell.org/package/apecs-0.6.0.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.7.0/revisions/
 - https://hackage.haskell.org/package/apecs-0.7.1/revisions/

The result of this upon the build-plans can be reviewed at

https://matrix.hackage.haskell.org/package/apecs@1549227956

This has started to propagate to other packages (e.g. `apecs-stm`) which are reverse dependencies and resulting in breaking build-plans for those packages until it was rectified via the metadata revision mentioned above.

We need your help! Please help us ensure a good user experience for users of Hackage/Cabal by the use of the [PVP](https://pvp.haskell.org/faq) mandated upper bounds in order to reduce the penalty on the Hackage infrastructure as well as to avoid unnecessary extra work for you as well as for us Hackage Trustees!

**Comment by jonascarpay** [comment]
Thank you for revising & reporting!
