### ISSUE TITLE
GHCJS runtime errors

### ISSUE THREAD

**Issue by NCrashed** [jonascarpay/apecs#31]
Hi, I was playing with apecs in GHCJS backend and found that some high level features are behaving wrong.

Here the repo with minimal Nix environment to reproduce the bug: https://github.com/NCrashed/apecs-ghcjs-tests

If I use `Cace` storage, I get the following runtime exception:
```
Cache miss!
CallStack (from HasCallStack):
  error, called at src/Apecs/Stores.hs:132:13 in apecs-0.7.2-CGfWKAFxnsuIyWdarfLW0G:Apecs.Stores
```

The code of apecs related part:
``` haskell
import Apecs
import Control.Monad
import Control.Monad.IO.Class

data ComponentA = ComponentA
  deriving (Show)

instance Component ComponentA where
  type Storage ComponentA = Map ComponentA

data ComponentB = ComponentB
  deriving (Show)

instance Component ComponentB where
  type Storage ComponentB = Cache 100 (Map ComponentB)

data ComponentC = ComponentC
  deriving (Show)

instance Component ComponentC where
  type Storage ComponentC = Cache 100 (Map ComponentC)

data World = World {
  worldAs :: !(Storage ComponentA)
, worldBs :: !(Storage ComponentB)
, worldCs :: !(Storage ComponentC)
, worldEs :: !(Storage EntityCounter)
}

instance Monad m => Has World m ComponentA where getStore = asks worldAs
instance Monad m => Has World m ComponentB where getStore = asks worldBs
instance Monad m => Has World m ComponentC where getStore = asks worldCs
instance Monad m => Has World m EntityCounter where getStore = asks worldEs

newWorld :: MonadIO m => m World
newWorld = do
  worldAs <- explInit
  worldBs <- explInit
  worldCs <- explInit
  worldEs <- explInit
  pure World{..}

issue01 :: MonadIO m => m ()
issue01 = do
  w <- newWorld
  runWith w $ do
    _ <- replicateM 10 $ void $ newEntity (ComponentA, ComponentB)
    cmapM_ $ \(a :: ComponentA, b :: ComponentB, e :: Entity) -> liftIO $ print e
```

**Comment by jonascarpay** [comment]
Thanks for the detailed report. I couldn't actually build the project, my PC runs out of memory.

Regardless, I have no idea what might be wrong here. It builds and runs fine on regular GHC (LTS-13.6). I'm not too familiar with GHCJS, is it common for a program to behave differently on it than on GHC?

**Comment by NCrashed** [comment]
Yep, unfortunately, it is required at minimum 16G of RAM to compile. I think, I will try to investigate the problem. 

It is not actually very common to behave different way than GHC version, it either not compiles or fail with runtime error due missing JS for C bits. It might be due unsafe vector operations.

**Comment by NCrashed** [comment]
I found core of the problem, after the call of the line https://github.com/jonascarpay/apecs/blob/master/apecs/src/Apecs/Stores.hs#L140 tags vector is filled with `0` instead of `-2`.

**Comment by NCrashed** [comment]
Created issue in reflex-platform repo https://github.com/reflex-frp/reflex-platform/issues/460

**Comment by dpwiz** [comment]
Is it working now?

**Comment by jonascarpay** [comment]
https://github.com/reflex-frp/reflex-platform/issues/460 has been closed, I'm guessing yes.
