### ISSUE TITLE
I think the function "cameraTransform" (in modle Apecs.Gloss) have some wrong.

### ISSUE THREAD

**Issue by Yang123321** [jonascarpay/apecs#35]
windowToWorld :: Camera -> (Float,Float) -> V2 Float
windowToWorld (Camera cx cs) (x,y) = V2 x y ^/ cs - cx

is should be :

windowToWorld :: Camera -> (Float,Float) -> V2 Float
windowToWorld (Camera cx cs) (x,y) = V2 x y ^/ cs + cx

**Comment by jonascarpay** [comment]
Fixed by #39
