### ISSUE TITLE
apecs-gloss hangs on exit

### ISSUE THREAD

**Issue by dpwiz** [jonascarpay/apecs#56]
Linux builds tend to halt indefinitely when using System.Exit. Not always, but quite often. Is there a canonical way to do a clean shutdown?

**Comment by jonascarpay** [comment]
Weird, I haven't experienced this myself. Have you tried whether this only happens in `apecs-gloss`, or if it also happens when you use `gloss` by itself?

**Comment by dpwiz** [comment]
This happens sporadically. Quite often on one of my machines and never(?) on others. The hunt continues.

I haven't seen that with my previous gloss apps.

**Comment by dpwiz** [comment]
The issues disappeared mysteriously after some system update.
