### ISSUE TITLE
Contrary to documentation modify/$~ is unsafe

### ISSUE THREAD

**Issue by dpwiz** [jonascarpay/apecs#62]
Here's it in its full glory (=

```
-- | Applies a function, if possible.
{-# INLINE modify #-}
modify, ($~) :: forall w m cx cy. (Get w m cx, Set w m cy) => Entity -> (cx -> cy) -> SystemT w m ()
modify (Entity ety) f = do
  sx :: Storage cx <- getStore
  sy :: Storage cy <- getStore
  lift$ do
    x <- explGet sx ety
    explSet sy ety (f x)
```

I don't know what "if possible" could mean here, since `explGet on `Map` store crashes and needs an additional `Maybe` wrapper.

Adding `explExists` check before getting `sx` helps, but I'm concerned about performance if the fix is applied by default. The additional check should be pretty cheap though, in *O(min(n,W))* as stated by `IntMap`.

I propose adding `unsafeModify` which skips the check and moving the default to the new non-crashing wrapper.

Alternatively, it's a documentation issue and just the description has to be corrected.
Relying on `$~` to do the right thing may or may not be a code smell leading to time spent on debugging "I do this thing but nothing happens" due to misplaced assumptions.

What do you think?

**Comment by jonascarpay** [comment]
Oops, accidentally closed the issue. Anyway, yeah, that definitely is a bug, weird that it's gone unnoticed this long. Thanks a lot for the PR! I don't think `unsafeModify` is worth having, please remove that and then I'll gladly merge :+1:

**Comment by dpwiz** [comment]
Done.
