### ISSUE TITLE
Replace monoid constraint for global components with custom typeclass

### ISSUE THREAD

**Issue by nmaehlmann** [jonascarpay/apecs#65]
The monoid constraint for global component seems to only be used for mempty. No usage of other monoid functions is mentioned in the documentation. It is bothersome to write semigroup (<>) instances when they are not used. A custom typeclass or something like this https://hackage.haskell.org/package/data-default which declares only a mempty equivalent would be nice.

**Comment by AnthonySuper** [comment]
This was discussed in #26

**Comment by nmaehlmann** [comment]
Sorry, I missed that. Thank you for the hint!
