### ISSUE TITLE
Community chat?

### ISSUE THREAD

**Issue by tdbgamer** [jonascarpay/apecs#85]
Is there a community Gitter, Discord, etc.? Would be cool to talk to people who are using this!

**Comment by dpwiz** [comment]
There are `#haskell-game:matrix.org` and `#apecs` on gamedev [discord](https://discord.gg/vxpWtBA).

**Comment by tdbgamer** [comment]
Thanks! Are they listed anywhere? There's no way I would've found this. Might be cool to put it in the readme or something?

**Comment by jonascarpay** [comment]
@dpwiz I'd like to bless some sort of community chat as the "official" one, what's your sense of what would be the best place for that? The gamedev discord?

**Comment by dpwiz** [comment]
We have a dedicated `#apecs` room in there. But discord is... discord and not everyone is okay with that.
Matrix has more active people, but people can be reluctant to ask away, esp. when there's an active conversation already.
I'd list discord and matrix both.
