### ISSUE TITLE
SystemT performance

### ISSUE THREAD

**Issue by jonascarpay** [jonascarpay/apecs#9]
I really want to merge the SystemT branch, there are a lot of neat things it allows for. Unfortunately, there is a performance hit that needs to be addressed first.

Changes:

- `System w a = SystemT w IO a`, and `SystemT w m a = ReaderT w m a`
- `Store s` is now `Store m s`, with e.g. `explGet s -> Int -> Stores s -> m ()`. `Store` instances have been changed to instances of `Store IO`.
- `Has` and `Log` have a similar new `m` argument.

The actual, non-type signature code is mostly intact, which suggests that the cause is type-related.

**Comment by isovector** [comment]
How are you measuring performance?

**Comment by jonascarpay** [comment]
With `stack bench`:
```
➜  apecs git:(master) stack bench
apecs-0.2.4.6: benchmarks
Running 1 benchmarks...
Benchmark apecs-bench: RUNNING...
benchmarking pos_vel/init
time                 238.2 μs   (236.3 μs .. 240.5 μs)
...
```
```
➜  apecs git:(systemt) stack bench
apecs-0.2.4.6: benchmarks
Running 1 benchmarks...
Benchmark apecs-bench: RUNNING...
benchmarking pos_vel/init
time                 2.061 ms   (2.032 ms .. 2.100 ms)
...
```

**Comment by robinp** [comment]
Shoot in the dark: Maybe https://www.stackbuilders.com/tutorials/haskell/ghc-optimization-and-fusion/ has some hints. Could SPECIALIZE on some instances help?

**Comment by tejon** [comment]
Paging @chrisdone and/or @Gabriel439

**Comment by cjenn** [comment]
I wanted to use part of this, so I created a toned-down version of the change. ([here](https://github.com/cjenn/apecs/tree/systemt-partial))

Simply replacing `System w` with `SystemT w IO` doesn't have any negative effects on performance.

**Comment by jonascarpay** [comment]
The systemt branch now contains a full SystemT implementation, with no performance cost. I also gave a few stores STM instances. This opens up a lot of possibilities, like running a System continuously on its own thread, without race conditions:
```haskell
forkSys $ forever (atomically (cmap f) >> sleep 1000)
```
Hackage upload soon
