### ISSUE TITLE
error destroying component for entity seemingly guaranteed to have that component

### ISSUE THREAD

**Issue by cosmicoptima** [jonascarpay/apecs#90]
the following code seems like it should work, but crashes at runtime:

```haskell
cmapM_ $ \(HasLocation _ _, entity) -> destroy entity (Proxy :: Proxy HasLocation)
```
with an error like `Reading non-existent Map component HasLocation for entity 89`

am i missing something? (in this case of course `HasLocation` is both the type and the constructor of that same type)

**Comment by cosmicoptima** [comment]
sure, i just produced the error with this: https://github.com/hackclub/rogue/blob/bug-investigation/src/Game.hs#L442

if it helps: `error, called at src/Apecs/Stores.hs:46:17 in apecs-0.9.3-7TgmL3aye7qLd0ypLZwGYF:Apecs.Stores`, and i can't think of any other call to apecs that could be raising this

**Comment by dpwiz** [comment]
I see there more places where `HasLocation` is requested irrefutably. You can try adding `HasCallStack` to all the functions doing that or do a profile build (no need to enable actual profiling).

**Comment by cosmicoptima** [comment]
oh, yeah, it is called from a completely different part of the program -- sorry about that!
