### ISSUE TITLE
Physics documentation is inaccurate

### ISSUE THREAD

**Issue by RegularTetragon** [jonascarpay/apecs#92]
The readme claims you can put the shape in the same constructor as a dynamic body:

```haskell
  let ballShape = cCircle 0.5
  newEntity ( DynamicBody
            , Shape ballShape
            , Position (V2 0 3)
            , Density 1
            , Elasticity 0.9
            , BodyPicture . color red . toPicture $ ballShape )
```

When in fact the type of the Shape constructor is

```haskell
Shape :: Entity -> Convex -> Shape
```

Requiring you to do
```haskell
  let ballShape = cCircle 0.5
  e <- newEntity ( DynamicBody
            , Position (V2 0 3)
            , Density 1
            , Elasticity 0.9
            , BodyPicture . color red . toPicture $ ballShape )
  newEntity $ Shape e ballShape
```
Or
```
  let ballShape = cCircle 0.5
  e <- newEntity ( DynamicBody
            , Position (V2 0 3)
            , Density 1
            , Elasticity 0.9
            , BodyPicture . color red . toPicture $ ballShape )
  set newEntity (Shape e ballShape)
```
I'm not sure that second one works either.

**Comment by RegularTetragon** [comment]
The readme claims you can put the shape in the same constructor as a dynamic body:

```haskell
  let ballShape = cCircle 0.5
  newEntity ( DynamicBody
            , Shape ballShape
            , Position (V2 0 3)
            , Density 1
            , Elasticity 0.9
            , BodyPicture . color red . toPicture $ ballShape )
```

When in fact the type of the Shape constructor is

```haskell
Shape :: Entity -> Convex -> Shape
```

Requiring you to do
```haskell
  let ballShape = cCircle 0.5
  e <- newEntity ( DynamicBody
            , Position (V2 0 3)
            , Density 1
            , Elasticity 0.9
            , BodyPicture . color red . toPicture $ ballShape )
  newEntity $ Shape e ballShape
```
Or
```
  let ballShape = cCircle 0.5
  e <- newEntity ( DynamicBody
            , Position (V2 0 3)
            , Density 1
            , Elasticity 0.9
            , BodyPicture . color red . toPicture $ ballShape )
  set newEntity (Shape e ballShape)
```
I'm not sure that second one works either.

**Comment by jonascarpay** [comment]
Oh, looks like you're right, not sure how that happened. Thanks! What's the reason for removing the `Picture` related stuff in #93?

**Comment by RegularTetragon** [comment]
I don't believe BodyPicture is in scope anywhere. I searched the master branch for it and only found it in the readme file. I might be wrong tho

**Comment by dpwiz** [comment]
https://github.com/jonascarpay/apecs/search?q=BodyPicture

**Comment by dpwiz** [comment]
A picture is produced by the [drawBody](https://hackage.haskell.org/package/apecs-gloss-0.2.4/docs/Apecs-Physics-Gloss.html#v:drawBody) system now.

**Comment by jonascarpay** [comment]
Ohhh right, thanks for looking into it. I suppose we should add the updated rendering code then. @RegularTetragon, would you mind adding that? If you're confused about anything, you can find type-checked versions of the code here:
https://github.com/jonascarpay/apecs/blob/master/examples/HelloWorld.hs
https://github.com/jonascarpay/apecs/blob/master/examples/Tumbler.hs
https://github.com/jonascarpay/apecs/blob/master/examples/Constraints.hs

**Comment by RegularTetragon** [comment]
I have added a line to the physics documentation on using drawBody, I hope it's sufficient
