### ISSUE TITLE
New article for Apecs - maybe depreciate outdated one?

### ISSUE THREAD

**Issue by Ashe** [jonascarpay/apecs#96]
Hey, thanks again for your incredible library :) 

After seeing people being mislead by my 4-year-old blog post both on discord and in issues like #87 , I thought I'd do another quick project and experiment with how things are done now. Sorry for self-advertising.

https://aas.sh/blog/notakto-a-haskell-game-with-apecs-and-raylib/

I don't know if you think this serves your post as much as my previous one does, but feel free to include it on your README as you see fit, maybe replacing my previous post or marking the old one as depreciated?

This post comes with a project as well: [Notakto](https://github.com/Ashe/Notakto/). I'll let you decide what you want to do with it.

Thank you again for your library, and my next project also uses apecs so expect more soon :)

**Comment by jonascarpay** [comment]
Awesome, this is very useful! I've replaced the previous link with links to both the game and blog post. Thanks, looking forward to hearing about your next project!
